### ISSUE TITLE
Documentation: Write a user story for Point Model

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/FLINT-UI#233]
### What is the current documentation state?

Currently, we don't have any specific documentation on specific user stories for FLINT-UI. We need to document them one by one to ensure users have an understanding base for getting started with FLINT models.

### Proposed Statement

Setup FLINT-UI locally or use the [temporary deployment available here](https://nice-bush-04fb02600.1.azurestaticapps.net/), and write a document about Point Model and how to use it. It should contain instructions around the usage of the model and what the specific data mean.

### Additional context.

Take assistance from the User Interface working group (`#user-interface`) on understanding more about FLINT-UI and how to employ it.

cc: @chicken-biryani @padmajabhol

**Comment by chicken-biryani** [comment]
A good start would be to learn what a user story is.

There are a lot of tools like Agile that will help you with it.

However, we would like to create a table in google docs for the user stories.

The template for the table is-

I want to (Task to be performed) | So that I can (Achieve goal) | Components involved | Additional notes.

Remember you don't have to fill all rows and column in a go. There will be places you don't understand things...

Go at your own pace and discuss with us... And keep us updated about your progress...

An informal conversation over slack works as well.

The task is a little lengthy but would help you get great insights and it would make you an extremely valuable contributor.

**Comment by Iheanacho-ai** [comment]
can i take this on, this seems like it would be a challenge and it is something i would absolutely love to try out

**Comment by arishmaurya** [comment]
@HarshCasper sir can i work on this if Iheanacho is not working on this ?

**Comment by rahulsh18** [comment]
hi @HarshCasper @chicken-biryani is this still being worked on? If not, I'd like to.

**Comment by chicken-biryani** [comment]
@rahulsh18 we may need some help with the FLINT Handbook... Maybe you could help us with that?

**Comment by rahulsh18** [comment]
oh for sure
