### ISSUE TITLE
Use `yarn` instead of `npm`

### ISSUE THREAD

**Issue by iamrajiv** [moja-global/FLINT-UI#47]
There are several benefits in using `yarn` over `npm`, most notably:

- Yarn strongly binds package versions
- Yarn can install packages from a local cache, not requiring network config
- Yarn installs packages in parallel, greatly improving performance
- Monorepo support (multiple packages) without the requirement for Lerna

**Comment by iamrajiv** [comment]
Also, we should adopt this across other moja global JavaScript-based projects. This will make everything consistent.
@aornugent @chicken-biryani @shubhamkarande13 @waridrox

**Comment by shubhamkarande13** [comment]
@iamrajiv 
Can we do this after mine and @waridrox 's LFX term is over? I can't deal with any more breaking changes at the moment.
We are really tired of spending a lot of time on fixing maintenance errors instead of focusing on new features. We have just two weeks left. I really feel guilty of spending two weeks on the graphs, that work should have been done in less than 3-4 days. 

 Everything is working right now. Please reopen this issue later. 

Thanks!

**Comment by waridrox** [comment]
Hi @iamrajiv, I think definitely using yarn instead of npm is a great choice but that would require refactoring the places where npm is being used currently. This might prove to be a blocker for our project since we are currently relying on npm for consistency. Maybe you could try on other repos which are not that active at the moment and come back later here... Thanks

**Comment by aornugent** [comment]
Good point @waridrox - timing is everything. But remember that issues are not sequential! We can work on multiple things at once. 

If moving to `yarn` is a good long term decision, which it sounds like you support, then we can demo it on a separate branch and only merge _when all tests pass and the other team members have reviewed and approved_.

**Comment by waridrox** [comment]
> If moving to yarn is a good long term decision, which it sounds like you support, then @iamrajiv can demo it on a separate branch and only merge when all tests pass and the other team members have reviewed and approved.

Sounds great !! ✨
